import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  learningPath: [
    'index',
    {
      type: 'category',
      label: '1. Foundations',
      collapsed: false,
      link: {type: 'generated-index', description: 'Prerequisite knowledge for understanding agentic AI.'},
      items: [
        'foundations/llm-fundamentals',
        'foundations/reasoning-models',
        'foundations/prompting-techniques',
        'foundations/embeddings-and-vector-stores',
        'foundations/rag-basics',
        'foundations/fine-tuning-overview',
        'foundations/evaluation-metrics',
      ],
    },
    {
      type: 'category',
      label: '2. Core Concepts',
      collapsed: false,
      link: {type: 'generated-index', description: 'What makes an AI system agentic.'},
      items: [
        'core-concepts/what-are-agents',
        'core-concepts/tools-and-function-calling',
        'core-concepts/model-context-protocol',
        'core-concepts/planning-and-reasoning',
        'core-concepts/memory-systems',
        'core-concepts/context-engineering',
        'core-concepts/agent-architectures',
        'core-concepts/agent-interop-protocols',
        'core-concepts/guardrails-and-safety',
      ],
    },
    {
      type: 'category',
      label: '3. Design Patterns',
      link: {type: 'generated-index', description: 'Proven patterns for building agent behaviors.'},
      items: [
        'design-patterns/react-pattern',
        'design-patterns/chain-of-thought',
        'design-patterns/tool-use-pattern',
        'design-patterns/reflection-pattern',
        'design-patterns/multi-agent-pattern',
        'design-patterns/plan-and-execute',
        'design-patterns/self-refinement',
        'design-patterns/human-in-the-loop',
      ],
    },
    {
      type: 'category',
      label: '4. Frameworks',
      link: {type: 'generated-index', description: 'Hands-on guides for popular agentic AI frameworks.'},
      items: [
        'frameworks/langchain-overview',
        'frameworks/langgraph-deep-dive',
        'frameworks/crewai-guide',
        'frameworks/autogen-guide',
        'frameworks/semantic-kernel',
        'frameworks/llamaindex-agents',
        'frameworks/openai-assistants-api',
        'frameworks/framework-comparison',
      ],
    },
    {
      type: 'category',
      label: '5. Code Walkthroughs',
      link: {type: 'generated-index', description: 'Pattern-focused code examples for building agentic AI systems.'},
      items: [
        'implementations/basic-react-agent',
        'implementations/rag-agent-with-tools',
        'implementations/multi-agent-crew',
        'implementations/langgraph-workflow',
        'implementations/tool-calling-agent',
        'implementations/evaluation-harness',
      ],
    },
  ],

  architectureDesign: [
    {
      type: 'category',
      label: 'Principles & Patterns',
      collapsed: false,
      link: {type: 'generated-index', description: 'Core principles for designing agentic systems at production scale.'},
      items: [
        'architecture-design/design-principles',
        'architecture-design/agent-orchestration-at-scale',
        'architecture-design/memory-and-state-management',
        'architecture-design/data-layer-design',
        'architecture-design/tool-registry-design',
        'architecture-design/multi-agent-communication',
        'architecture-design/error-handling-and-recovery',
        'architecture-design/observability-and-tracing',
        'architecture-design/security-considerations',
        'architecture-design/hallucination-mitigation',
        'architecture-design/production-issues-and-debugging',
      ],
    },
    {
      type: 'category',
      label: 'Architecture Design Questions',
      collapsed: false,
      link: {type: 'generated-index', description: 'Interview-ready system design walkthroughs with architecture diagrams and trade-off analysis.'},
      items: [
        'architecture-design/customer-support-agent',
        'architecture-design/code-assistant',
        'architecture-design/research-agent',
        'architecture-design/data-pipeline-agent',
        'architecture-design/content-moderation',
        'architecture-design/document-processing',
        'architecture-design/trading-agent',
        'architecture-design/observability-platform',
        'architecture-design/healthcare-assistant',
        'architecture-design/devops-agent',
        'architecture-design/agent-memory-system',
        'architecture-design/agent-evaluation-platform',
        'architecture-design/workflow-orchestrator',
        {
          type: 'category',
          label: 'Domain-Specific: AEC & Manufacturing',
          collapsed: true,
          link: {type: 'generated-index', description: 'Architecture designs for architecture, engineering, construction, and manufacturing domains.'},
          items: [
            'architecture-design/domain/chatgpt-for-autodesk',
            'architecture-design/domain/cad-modifier-agent',
            'architecture-design/domain/building-plan-generator',
            'architecture-design/domain/design-review-system',
            'architecture-design/domain/rag-engineering-docs',
          ],
        },
      ],
    },
  ],

  projects: [
    {
      type: 'category',
      label: 'Real-World Projects',
      collapsed: false,
      link: {type: 'generated-index', description: 'Full implementations with runnable code, framework decision rationale, and setup instructions.'},
      items: [
        'projects/customer-support-agent',
        'projects/research-agent',
        'projects/code-assistant-agent',
        'projects/data-pipeline-agent',
        'projects/llm-gateway',
        'projects/agent-evaluation-framework',
        'projects/multi-agent-orchestration',
        'projects/production-rag-engine',
        'projects/event-driven-agent',
      ],
    },
  ],

  interviewPrep: [
    {
      type: 'category',
      label: 'Interview Questions',
      collapsed: false,
      link: {type: 'generated-index', description: 'Comprehensive question bank for agentic AI interviews.'},
      items: [
        'interview-questions/foundational-qa',
        'interview-questions/agent-architecture-qa',
        'interview-questions/design-pattern-qa',
        'interview-questions/framework-qa',
        'interview-questions/coding-challenges',
        'interview-questions/behavioral-and-scenario',
      ],
    },
  ],
};

export default sidebars;
